### ISSUE TITLE
Create New Evidence drawer

### ISSUE THREAD

**Issue by gurunate** [gurunate/learning-portrait#126]
![Image](https://github.com/gurunate/learning-portrait/assets/742500/34b02e32-7a94-45d7-b929-a1b473c29e21)

https://www.figma.com/design/AnL18DKGLfAfbF7G0QdcfU/Learning-Portrait-2.0?node-id=3883-7071&t=Z5xmEBOJ8v79tFGJ-4

**Comment by hannamlittlefield** [comment]
@wartowski @gurunate 
- Upload image component should be smaller
- remove 'Image' title from image component
- Put the upload component on bottom 
- Change rounded edges on the drawer
- Next to Students label - have a switch instead of radio buttons -> 
If coming from the evidence page: the switch defaults to All Students, but have "Specific Students" available. If 'Specific Students' is selected - student multiselect appears
If coming from specific student page -> Default to that student

**Comment by wartowski** [comment]
(and if coming from specific student page, maintain drop down for students so could add other students also.)

otherwise- I think you captured it all!
